name: car-model-classification
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow
  - keras
  - opencv
  - jupyter
  - pip
  - pip:
      - imageio
      - tqdm
      - pyyaml